version: '3.1'
services:

  database:
    image: mysql:8.0.19
    container_name: ecommerce_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3316:3306"
    networks:
      ecommerce_default:
        ipv4_address: 10.1.0.101

networks:
  ecommerce_default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
